sudo: required
dist: bionic

addons:
  apt:
    packages:
      - build-essential
      - curl
      - cmake
      - ninja-build
      - python3
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - flex
      - byacc
      - libnuma-dev

branches:
  only:
    - dev

matrix:
  include:
    - language: rust
      rust:
        - stable
        - beta
        - nightly
      jobs:
        allow_failures:
          - rust: nightly
        fast_finish: true
      cache: cargo

      before_script:
        - pip3 install meson
        - mkdir build && cd build && cmake .. && make install
      script:
        - cargo build --verbose --all
        - cargo test --verbose --all
