dist: bionic
os: linux
language: rust
cache:
  cargo: true
  directories:
    - build
rust:
  - stable

addons:
  apt:
    packages:
      - build-essential
      - curl
      - cmake
      - ninja-build
      - python3
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - flex
      - byacc
      - libnuma-dev
      - llvm
      - clang
      - libunwind-dev

branches:
  only:
    - master

jobs:
  fast_finish: true

before_script:
  - pip3 install meson
script:
  - bash ./build.sh
