dist: bionic
os: linux
arch:
  - amd64
  - arm64
language: rust
cache:
  cargo: true
  directories:
    - build
rust:
  - stable

addons:
  apt:
    packages:
      - build-essential
      - curl
      - ninja-build
      - python3
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - flex
      - byacc
      - libnuma-dev
      - llvm
      - clang
      - libunwind-dev

branches:
  only:
    - master

jobs:
  fast_finish: true

before_install:
  - wget https://github.com/Kitware/CMake/releases/download/v3.19.6/cmake-3.19.6-Linux-$(uname -m).sh
install:
  - chmod +x cmake-3.19.6-Linux-$(uname -m).sh
  - mkdir -p build/install
  - ./cmake-3.19.6-Linux-$(uname -m).sh --skip-license --prefix=${PWD}/build/install --exclude-subdir
  - export PATH="${PWD}/build/install/bin:${PATH}"

before_script:
  - pip3 install meson
script:
  - bash ./build.sh
