sudo: required

addons:
  apt:
    packages:
      - build-essential
      - curl
      - cmake
      - meson
      - libpcap-dev

branches:
  only:
  - dev

matrix:
  include:
    - language: rust
      rust:
        - stable
        - beta
        - nightly
      jobs:
        allow_failures:
          - rust: nightly
        fast_finish: true
      cache: cargo

      script:
        - cargo build --verbose --all
        - cargo test --verbose --all
