[package]
name = "alphonse"
version = "0.1.0"
authors = ["Jack Liar <15205739+JackLiar@users.noreply.github.com>"]
edition = "2018"

[dependencies]
clap = "2.33.1"
crossbeam-channel = "0.4.2"
libc = "0.2.71"
path-absolutize = "2.0.2"
pcap = "0.7.0"
twox-hash = { git = "https://github.com/flier/twox-hash.git", branch="xxh3" }
yaml-rust = "0.4.4"

[build-dependencies]
cpp_build = "0.5.4"
bindgen = "0.54.0"

# [features]
# dpdk=[]
