[package]
name = "alphonse"
version = "0.1.0"
authors = ["Jack Liar <15205739+JackLiar@users.noreply.github.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
arc-swap = "*"
clap = "2.33.3"
crossbeam-channel = "0.5"
libc = "0.2"
libloading = "0.6"
path-absolutize = "3.0.6"
pcap = "0.7.0"
serde_json = "1.0"
signal-hook = "0.1.16"
twox-hash = { git = "https://github.com/flier/twox-hash.git", branch = "xxh3" }
yaml-rust = "0.4.4"

[dependencies.alphonse-api]
path = "./src/api"
optional = false

[dependencies.hyperscan]
version = "0.2.0"
features = ["chimera"]

[build-dependencies]
cpp_build = { version = "0.5.5", optional = true }
bindgen = { version = "0.55.1", optional = true }

[features]
dpdk = ["cpp_build", "bindgen"]
heuristic-mpls = []
