[package]
name = "alphonse"
version = "0.1.0"
authors = ["Jack Liar <15205739+JackLiar@users.noreply.github.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.31"
clap = "2.33.1"
crossbeam-channel = "0.4.2"
libc = "0.2.71"
libloading = "0.6.2"
# llhttp = {git = "https://github.com/JackLiar/rust-llhttp.git", branch="dev"}
path-absolutize = "3.0.2"
pcap = "0.7.0"
serde_json = "1.0.55"
signal-hook = "0.1.16"
twox-hash = { git = "https://github.com/flier/twox-hash.git", branch = "xxh3" }
yaml-rust = "0.4.4"

[dependencies.hyperscan]
version = "0.2.0"
features = ["chimera"]

[build-dependencies]
cpp_build = { version = "0.5.4", optional = true }
bindgen = { version = "0.54.0", optional = true }

[features]
dpdk = ["cpp_build", "bindgen"]
