[package]
name = "alphonse"
version = "0.1.0"
authors = ["Jack Liar <15205739+JackLiar@users.noreply.github.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
# arc-swap = "1.1"
clap = "2.33.3"
crossbeam-channel = "0.5"
libc = "0.2"
libloading = "0.6"
path-absolutize = "3.0"
pcap = "0.7.0"
serde_json = "1.0"
signal-hook = "0.3"
twox-hash = "1.6"
yaml-rust = "0.4.4"
rte = { git = "https://github.com/JackLiar/rust-dpdk.git", optional = true }

[dependencies.alphonse-api]
path = "../api"
optional = false
version = "0.1.0"

[dependencies.hyperscan]
version = "0.2.0"
features = ["chimera"]

[features]
dpdk = ["rte"]
heuristic-mpls = []
